server {
    listen 80;
    client_max_body_size 50M;

    # Rule for serving specific root files (e.g., for SEO).
    # The '=' makes this an exact and high-priority match.
    location = /robots.txt { root /app/public; }
    location = /sitemap.xml { root /app/public; }

    # Rule for serving the /static directory.
    # Nginx is much faster at this than Flask.
    location /static/ {
        alias /app/bundle/static/;
    }



    # Rule to pass all other requests to the Flask application.
    location / {
        proxy_pass http://trace_it_app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}